### ISSUE TITLE
Month error 

### ISSUE THREAD

**Issue by milanPansuriya** [shagiz/AlmostMaterialDatepicker#2]
Hey @shagiz you had forgotten to add +1 for getting month 
 [Replaec your method with this](https://github.com/shagiz/AlmostMaterialDatepicker/blob/master/library/src/main/java/com/shagi/materialdatepicker/date/DatePickerFragmentDialog.java)

public void notifyOnDateListener() {
        if (mCallBack != null) {
            mCallBack.onDateSet(DatePickerFragmentDialog.this, mCalendar.get(Calendar.YEAR),
                    mCalendar.get(Calendar.MONTH)+1, mCalendar.get(Calendar.DAY_OF_MONTH));
        }
    }

**Comment by shagiz** [comment]
Hello, @milanPansuriya! Thank you for response, but there is no error, because of using Calendar class.
You can try this sample and see that month with number 11 will give you december:
```
val dialog = DatePickerFragmentDialog.newInstance({ view, year, monthOfYear, dayOfMonth ->
                val calendar = Calendar.getInstance()
                calendar.set(year, monthOfYear, dayOfMonth)

                val simpleDateFormat = SimpleDateFormat("yyyy-MMM-dd", Locale.getDefault())

                Toast.makeText(applicationContext, simpleDateFormat.format(calendar.time), Toast.LENGTH_SHORT).show()
            }, 2017, 11, 4)
```
